dist: trusty
sudo: required
language: python
python:
- '3.6'
services:
- redis-server
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
- sudo add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu
  trusty/'
- sudo apt-get update
- sudo apt-get install r-base
install:
- pip install -r requirements.txt
- sh travis/setup.sh
script:
- coverage run --source=build_manager,cookiecutter_manager,coverage_manager,dataschema_manager,docs_manager,experiments_manager,git_manager,helpers,marketplace,pylint_manager,quality_manager,requirements_manager,recommendations,user_manager,
  manage.py test
after_success: coveralls
